version: "3.4"
services:
  control-center:
    build:
       context: .
       cache_from:
           - confluentinc/cp-enterprise-control-center:5.3.0 
    container_name: control-center
    restart: always
    ports:
      - "9021:9021"
      - "9022:9022"
    volumes:
      - $PWD/scripts/security:/etc/kafka/secrets
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "<CLUSTER1_URL>"
      CONTROL_CENTER_STREAMS_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: HTTPS
      CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL: SASL_SSL
      CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"<CLUSTER1_APIKEY>\" password=\"<CLUSTER1_SECRET>\";"
      CONTROL_CENTER_STREAMS_SASL_MECHANISM: PLAIN
      CONTROL_CENTER_REPLICATION_FACTOR: 3
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
      CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES: 8388608
      CONTROL_CENTER_LICENSE: <LICENSE_KEY>
      ADDITIONAL_PROPS: confluent.controlcenter.kafka.cloud1.bootstrap.servers=<CLUSTER2_BOOTSTRAP_SERVER>\nconfluent.controlcenter.kafka.cloud1.security.protocol=SASL_SSL\nconfluent.controlcenter.kafka.cloud1.sasl.mechanism=PLAIN\nconfluent.controlcenter.kafka.cloud1.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"<CLUSTER2_API_KEY>\" password=\"<CLUSTER2_SECRET>\"; 
